[package]
name = "movectf"
version = "0.0.1"

[dependencies]
Sui = { local = "/Users/icefox/Workspace/sui/crates/sui-framework" }

[addresses]
movectf =  "0x0"
sui =  "0000000000000000000000000000000000000002"
