[package]
name = "catch_flag"
version = "0.0.7"

[dependencies]
Sui = { local = "/Users/icefox/Workspace/sui/crates/sui-framework" }
ctf = { local = "../game" }

[addresses]
catch_flag =  "0x0"
sui =  "0000000000000000000000000000000000000002"
