[package]
name="MovectfAnswer2"
version="0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }

[addresses]
movectf_answer2="0x0"
sui="0x2"
